name: Run Modelling Script

on:
  repository_dispatch:
    types: [triggering-modelling]
  workflow_dispatch: # allows manual triggering from GitHub UI

jobs:
  run-experiment:
    runs-on: ubuntu-latest
    env:
      ENV: production
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r MLProject/requirements.txt

      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local | tee mlflow_output.log

      - name: Extract MLflow Run ID from logs
        run: |
          RUN_ID=$(grep -oP 'MLFLOW_RUN_ID=\K[a-f0-9\-]+' mlflow_output.log)
          echo "Extracted Run ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Build Docker Image from MLflow Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/modelling" --name ekstrovert-introvert-behavior
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: docker tag ekstrovert-introvert-behavior ${{ secrets.DOCKERHUB_USERNAME }}/sd-cc:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/sd-cc:latest

      - name: Upload Trained Model Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: trained-model
          path: MLProject/output/